# Generated by Django 2.2.5 on 2021-07-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=100)),
                ('modified', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rotation_period', models.CharField(max_length=100)),
                ('orbital_period', models.CharField(max_length=100)),
                ('diameter', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('gravity', models.CharField(max_length=100)),
                ('terrain', models.CharField(max_length=100)),
                ('surface_water', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=100)),
                ('modified', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('mass', models.CharField(max_length=100)),
                ('hair_color', models.CharField(max_length=100)),
                ('skin_color', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhabitants', to='api.Planet')),
            ],
        ),
    ]
