# Generated by Django 2.2.5 on 2021-07-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210725_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
