# Generated by Django 2.2.5 on 2021-07-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210725_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode_id',
            field=models.IntegerField(),
        ),
    ]
